-- Generated by `python -m docduckdb schema --write`. Do not hand-edit.
--
-- Columns are declared, not inferred. read_json_auto samples the head of a file
-- by default; the head of a sweep is mostly successes, so error_kind would type
-- from nulls and the refusal rows would drop out on this side of the contract.

create or replace view sweep as
select * from read_json(
    'out/*/sweep.jsonl',
    format = 'newline_delimited',
    columns = {'sweep_id': 'VARCHAR', 'label': 'VARCHAR', 'root': 'VARCHAR', 'started_utc': 'VARCHAR', 'finished_utc': 'VARCHAR', 'walk_s': 'DOUBLE', 'elapsed_s': 'DOUBLE', 'jobs': 'BIGINT', 'hashed': 'BOOLEAN', 'extensions': 'VARCHAR', 'files_seen': 'BIGINT', 'files_attempted': 'BIGINT', 'files_ok': 'BIGINT', 'files_failed': 'BIGINT', 'blocks_written': 'BIGINT', 'source_bytes': 'BIGINT', 'document_bytes': 'BIGINT', 'block_bytes': 'BIGINT', 'tool_version': 'VARCHAR', 'python_version': 'VARCHAR', 'platform': 'VARCHAR', 'backends': 'JSON'}
);

create or replace view document_all as
select * from read_json(
    'out/*/document.jsonl',
    format = 'newline_delimited',
    columns = {'sweep_id': 'VARCHAR', 'doc_id': 'VARCHAR', 'path': 'VARCHAR', 'ext': 'VARCHAR', 'format': 'VARCHAR', 'size_bytes': 'BIGINT', 'modified_utc': 'VARCHAR', 'content_sha256': 'VARCHAR', 'backend': 'VARCHAR', 'backend_version': 'VARCHAR', 'ok': 'BOOLEAN', 'error_kind': 'VARCHAR', 'error_detail': 'VARCHAR', 'elapsed_ms': 'DOUBLE', 'format_version': 'VARCHAR', 'page_count': 'BIGINT', 'slide_count': 'BIGINT', 'sheet_count': 'BIGINT', 'block_count': 'BIGINT', 'char_count': 'BIGINT', 'title': 'VARCHAR', 'author': 'VARCHAR', 'subject': 'VARCHAR', 'keywords': 'VARCHAR', 'creator': 'VARCHAR', 'producer': 'VARCHAR', 'created_declared': 'VARCHAR', 'modified_declared': 'VARCHAR'}
);

create or replace view block_all as
select * from read_json(
    'out/*/block.jsonl',
    format = 'newline_delimited',
    columns = {'sweep_id': 'VARCHAR', 'doc_id': 'VARCHAR', 'block_index': 'BIGINT', 'part_kind': 'VARCHAR', 'part_index': 'BIGINT', 'part_label': 'VARCHAR', 'block_kind': 'VARCHAR', 'text': 'VARCHAR', 'char_count': 'BIGINT', 'char_start': 'BIGINT', 'char_end': 'BIGINT', 'byte_start': 'BIGINT', 'byte_end': 'BIGINT', 'box_x0': 'DOUBLE', 'box_y0': 'DOUBLE', 'box_x1': 'DOUBLE', 'box_y1': 'DOUBLE', 'box_of': 'VARCHAR', 'style_name': 'VARCHAR', 'shape_name': 'VARCHAR', 'cell_ref': 'VARCHAR'}
);

-- The most recent sweep. Ties break on sweep_id, which carries the same clock.
create or replace view latest_sweep as
select sweep_id from sweep order by started_utc desc, sweep_id desc limit 1;

create or replace view document as
select * from document_all
where sweep_id = (select sweep_id from latest_sweep);

create or replace view block as
select * from block_all
where sweep_id = (select sweep_id from latest_sweep);
